### ISSUE TITLE
[CI] Auto Deploy to Private Cloud Infra

### ISSUE THREAD

**Issue by JacobLinCool** [UniCourse-TW/Backend#22]
Thanks to [CNTUG](https://cloudnative.tw/) for providing the cloud infra for this project.

It's time to make our workflow more efficient and help us to focus on the core development of UniCourse.

## What to do

The following may be done by GitHub Actions:

**_On PR Open / Update_**

* Build the docker image with the PR id as the tag and push it to GHCR.
* SSH to our private cloud infra, pull the tagged image, and run the backend server.
* Say something in the PR to notify about the deployment.

**_On PR Close_**

* SSH to our private cloud infra, stop the backend server and remove the image.

**_On main branch Push_**

* Build the docker image with the `latest` tag and push it to GHCR.
* SSH to our private cloud infra, pull the `latest` image, and run the backend server.

## Notes

To avoid the port conflict, we need to use a different port for each deployment. The port number can be automatically configured in the `.env` file in each deployment.

If we transfer our domain to Cloudflare, we can use [Cloudflare Tunnel](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps) as a reverse proxy to expose the backend server to the internet with different subdomains for each deployment, e.g. `pr-1234.unicourse.tw`.

**Comment by Bogay** [comment]
Auto deploy for latest release is completed by #52 #53 

Deploy for each PR might need more discussion.

**Comment by skyhong2002** [comment]
Can I consider this task done? @Bogay

**Comment by skyhong2002** [comment]
@Bogay 表示後端不需要 Auto Deploy，想知道 @JacobLinCool 的想法

**Comment by SiongSng** [comment]
我自己是覺得後端只需要自動部屬生產狀態的即可
個別 PR 沒有必要
