### ISSUE TITLE
Import 111-2 Courses from NTNU

### ISSUE THREAD

**Issue by skyhong2002** [UniCourse-TW/Backend#58]
As the title described, it will be much more better if we upload the next semester of the courses.

**Comment by skyhong2002** [comment]
@JacobLinCool 目前在 unicourse.tw 上匯入的課程似乎 111-1 的課程都同時有兩個，而且還看不到 111-2 的課程ㄛ

![Image](https://user-images.githubusercontent.com/29522167/210071925-8c068e96-b163-474e-9301-d3f8ca334db1.png)

**Comment by uier** [comment]
it's a bug in front-end

move this issue to https://github.com/UniCourse-TW/Frontend/issues/70
